name: Notify Marketplace on Update

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Extract skill name
        id: skill
        run: |
          # Extract skill name from repository name
          REPO_NAME="${{ github.event.repository.name }}"
          SKILL_NAME="${REPO_NAME%-skill}"
          echo "name=$SKILL_NAME" >> $GITHUB_OUTPUT

      - name: Send repository dispatch to marketplace
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MARKETPLACE_SYNC_TOKEN }}
          repository: netresearch/claude-code-marketplace
          event-type: skill-updated
          client-payload: |
            {
              "skill": "${{ steps.skill.outputs.name }}",
              "version": "${{ github.event.release.tag_name || 'main' }}",
              "ref": "${{ github.sha }}"
            }

      - name: Summary
        run: |
          echo "✓ Marketplace sync triggered"
          echo "Skill: ${{ steps.skill.outputs.name }}"
          echo "Event: ${{ github.event_name }}"
